### PR TITLE
Update to use mwdebug1001/2

### PR DESCRIPTION
**Pull request by addshore**

### CODE REVIEW

**Comment by hashar** [comment]
Poke @Paladox

**Comment by paladox** [comment]
+1, thanks.

**Comment by bd808** [comment]
Doh! I made these changes myself before I got around to checking my email for the day. See 55cf22654ccca32adf0347d87c6946613e8f6b28. A new v0.8.3 package has been submitted to Mozilla for review.

**Comment by addshore** [comment]
@bd808 it looks like I missed one occourance of mw1017 in my PR anyway!
Thanks for your change!

**Pull request closed without merging**
